name: Pull Request Compliance
on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x.x
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint


  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x.x
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build