name: Publish to npm
on:
  workflow_dispatch:

jobs:
  publish-release:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x.x
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: npm publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
